name: Golang with NVS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Nexus Vulnerability Scanner
      uses: sonatype/nvs-github-action@releases/v1.0.0
      with:
        email: ihighend@gmail.com
        password: admin123
        directory: ./
