name: Golang with NVS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Nexus Vulnerability Scanner
      uses: sonatype/nvs-github-action@develop-with-node-modules
      with:
        email: mshevelov+13@sonatype.com
        password: admin123
        directory: ./
